#!/usr/bin/env bash
set -e
rm -f *.png
krita character_01_walk_up.kra --export-sequence --export-filename character_01_walk_up_.png
krita character_01_walk_down.kra --export-sequence --export-filename character_01_walk_down_.png
krita character_01_walk_left.kra --export-sequence --export-filename character_01_walk_left_.png
krita character_01_walk_right.kra --export-sequence --export-filename character_01_walk_right_.png
krita character_01_walk_upleft.kra --export-sequence --export-filename character_01_walk_upleft_.png
krita character_01_walk_downleft.kra --export-sequence --export-filename character_01_walk_downleft_.png
krita character_01_walk_upright.kra --export-sequence --export-filename character_01_walk_upright_.png
krita character_01_walk_downright.kra --export-sequence --export-filename character_01_walk_downright_.png
krita character_01_die_up.kra --export-sequence --export-filename character_01_die_up_.png
krita character_01_die_down.kra --export-sequence --export-filename character_01_die_down_.png
krita character_01_die_left.kra --export-sequence --export-filename character_01_die_left_.png
krita character_01_die_right.kra --export-sequence --export-filename character_01_die_right_.png
krita character_01_die_upleft.kra --export-sequence --export-filename character_01_die_upleft_.png
krita character_01_die_downleft.kra --export-sequence --export-filename character_01_die_downleft_.png
krita character_01_die_upright.kra --export-sequence --export-filename character_01_die_upright_.png
krita character_01_die_downright.kra --export-sequence --export-filename character_01_die_downright_.png

cp tileset/*.png .
cp blob/*.png .

rm -rf ../sprite_sheets/*.png ../sprite_sheets/*.ron
sheep pack character_0*.png \
--out ../sprite_sheets/character_0 \
--packer maxrects \
--pretty \
--format amethyst_named
sheep pack dungeon_walls_*.png blob_*.png dungeon_tiles_*.png \
--out ../sprite_sheets/tiles \
--packer maxrects \
--pretty \
--format amethyst_named
